name: "Twitter Header with Blog Posts"
author: "Simon Wicki"
description: "Automatically update your Twitter header with your latest blog posts—among arbitrary text and images."
inputs:
  BLOG_RSS:
    description: "supported blog RSS feed url. e.g. https://dev.to/feed/zwacky, https://medium.com/feed/@zwacky, https://zwacky.hashnode.dev/rss.xml"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "twitter"
  color: "blue"